const { test, expect } = require('@playwright/test')
const AxeBuilder = require('@axe-core/playwright').default
const fs = require('node:fs')
const root = process.env.VISUAL_ARTIFACT_ROOT || 'artifacts/focus-hub'

async function login(page) {
  await page.goto('/login')
  await page.getByLabel('Email').fill(process.env.SMOKE_EMAIL)
  await page.getByLabel('Password', { exact: false }).fill(process.env.SMOKE_PASSWORD)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page).toHaveURL(/\/today$/, { timeout: 15000 })
}

async function api(page, path, body) {
  return page.evaluate(async ({ path, body }) => {
    const headers = { 'Content-Type': 'application/json', ClientActionId: crypto.randomUUID() }
    if (body) headers['X-CSRF-TOKEN'] = (await (await fetch('/api/v1/auth/csrf')).json()).requestToken
    const response = await fetch('/api/v1' + path, body ? { method: 'POST', headers, body: JSON.stringify(body) } : {})
    if (!response.ok) throw new Error(`Fixture request failed: ${response.status}`)
    return response.json()
  }, { path, body })
}

test('focus hub fits its viewport and preserves real sessions, settings and cities', async ({ page, browserName }) => {
  test.setTimeout(180000)
  page.setDefaultTimeout(15000)
  const errors = []; page.on('pageerror', error => errors.push(error.message))
  await login(page)
  await page.goto('/focus')
  await expect(page.getByRole('button', { name: 'Start focus', exact: true })).toBeEnabled()
  await page.evaluate(() => document.fonts.ready)
  fs.mkdirSync(root, { recursive: true })
  for (const [width, height] of [[1920, 1080], [1366, 768], [768, 1024], [390, 844]]) {
    await page.setViewportSize({ width, height })
    await expect(page.getByRole('button', { name: 'Start focus', exact: true })).toBeInViewport()
    await page.screenshot({ path: `${root}/${browserName}-focus-${width}.png`, fullPage: true })
    const dimensions = await page.evaluate(() => ({ scroll: document.documentElement.scrollHeight, height: innerHeight, width: innerWidth, contentWidth: document.documentElement.scrollWidth }))
    expect(dimensions.contentWidth).toBeLessThanOrEqual(width)
    if (width >= 1366) expect(dimensions.scroll).toBeLessThanOrEqual(height + 1)
    const image = page.locator('img[src="/images/Background%20upgrade.png"]')
    const bounds = await image.boundingBox()
    expect(await image.evaluate(element => [element.naturalWidth, element.naturalHeight])).toEqual([1672, 941])
    if (width >= 1366) {
      expect(Math.abs(bounds.width - width)).toBeLessThan(1)
      expect(Math.abs(bounds.height - height)).toBeLessThan(1)
      expect(Math.abs(bounds.x)).toBeLessThan(1)
      expect(Math.abs(bounds.y)).toBeLessThan(1)
      await expect(page.getByRole('progressbar', { name: 'Daily focus progress' })).toBeInViewport()
    }
    const heading = await page.getByRole('heading', { name: 'Focus', exact: true }).boundingBox()
    expect(heading.y).toBeGreaterThanOrEqual(width >= 1200 ? 72 : 64)
    await page.screenshot({ path: `${root}/${browserName}-focus-${width}.png`, fullPage: true })
  }
  const axe = await new AxeBuilder({ page }).analyze()
  expect(axe.violations).toEqual([])
  await page.setViewportSize({ width: 1366, height: 768 })
  await page.getByRole('button', { name: 'Edit daily goal' }).click()
  await page.getByLabel('Hours', { exact: true }).fill('4')
  await page.getByRole('button', { name: 'Save daily goal' }).click()
  await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuemax', '240')
  await page.getByRole('button', { name: /Deep Work 90/ }).click()
  await expect(page.getByRole('timer')).toHaveText('01:30:00')
  const clock = await page.getByRole('timer').evaluate(element => ({ text: element.getBoundingClientRect().width, face: element.parentElement.parentElement.getBoundingClientRect().width }))
  expect(clock.text).toBeLessThanOrEqual(clock.face)
  await page.getByRole('button', { name: /Smart Focus Suggested rhythm/ }).click()
  await expect(page.getByRole('button', { name: 'Start focus', exact: true })).toBeDisabled()
  expect(await page.evaluate(() => document.documentElement.scrollHeight)).toBeLessThanOrEqual(769)
  await page.getByRole('button', { name: 'Review schedule' }).click()
  const schedule = page.getByRole('dialog', { name: 'Suggested focus rhythm' })
  await expect(schedule.locator('ol li')).toHaveCount(4)
  await expect(schedule.locator('ol li').first()).toHaveText('Focus50 min')
  await schedule.getByRole('button', { name: 'Use this schedule' }).click()
  await expect(page.getByRole('button', { name: 'Start focus', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: /Pomodoro 25/ }).click()
  await page.getByRole('button', { name: 'Focus settings', exact: true }).click()
  const settings = page.getByRole('dialog', { name: 'Focus settings' })
  await settings.getByLabel('Focus minutes', { exact: true }).fill('1')
  await settings.getByLabel('Break minutes', { exact: true }).fill('1')
  await settings.getByLabel('Volume', { exact: true }).fill('17')
  await settings.getByLabel('Sound', { exact: true }).selectOption('Warm Gong')
  await settings.getByRole('button', { name: 'Preview sound' }).click()
  await settings.getByRole('button', { name: 'Save settings' }).click()
  await expect(settings).not.toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'Focus settings', exact: true }).click()
  await expect(page.getByLabel('Volume', { exact: true })).toHaveValue('17')
  await expect(page.getByLabel('Sound', { exact: true })).toHaveValue('Warm Gong')
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: /Custom Your rhythm/ }).click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('timer')).toHaveText('01:00')
  expect(await page.evaluate(() => document.documentElement.scrollHeight)).toBeLessThanOrEqual(769)
  await page.getByRole('button', { name: /Pomodoro 25/ }).click()
  await page.getByRole('button', { name: 'Start focus', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Pause', exact: true })).toBeVisible()
  for (const [width, height] of [[1920, 1080], [1366, 768]]) {
    await page.setViewportSize({ width, height })
    for (const mode of ['Timer', 'Stopwatch', 'World Clock']) {
      await page.getByRole('tab', { name: mode, exact: true }).click()
      if (mode === 'World Clock') await expect(page.getByRole('heading', { name: 'Sydney' })).toBeVisible()
      await page.screenshot({ path: `${root}/${browserName}-active-${mode.replaceAll(' ', '-')}-${width}.png`, fullPage: true })
      expect(await page.evaluate(() => document.documentElement.scrollHeight)).toBeLessThanOrEqual(height + 1)
      await expect(page.getByRole('progressbar')).toBeInViewport()
    }
  }
  await page.getByRole('tab', { name: 'Focus', exact: true }).click()
  await page.getByRole('link', { name: 'Return to Today', exact: false }).click()
  await page.getByRole('link', { name: /Continue focus/ }).click()
  await expect(page.getByRole('button', { name: 'Pause', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Resume', exact: true })).toBeVisible()
  const remaining = await page.getByRole('timer').textContent()
  await page.reload()
  await expect(page.getByRole('button', { name: 'Resume', exact: true })).toBeVisible()
  await expect(page.getByRole('timer')).toHaveText(remaining)
  await page.getByRole('button', { name: 'Resume', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Pause', exact: true })).toBeVisible()
  await page.evaluate(() => document.dispatchEvent(new Event('freeze')))
  await expect(page.getByRole('heading', { name: 'Focus was interrupted' })).toBeVisible()
  await page.screenshot({ path: `${root}/${browserName}-recovery.png`, fullPage: true })
  await page.getByRole('button', { name: 'Resume with remaining time' }).click()
  await expect(page.getByRole('button', { name: 'Pause', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Stop', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Start focus', exact: true })).toBeVisible()
  for (const [label, path, field] of [['Tasks', 'tasks', 'taskId'], ['Goals', 'goals', 'goalId'], ['Habits', 'habits', 'habitId']]) {
    const title = `Focus hub ${path} fixture`
    const entity = await api(page, '/' + path, { title })
    await page.getByRole('button', { name: '+ Choose task, goal or habit' }).click()
    const picker = page.getByRole('dialog', { name: 'Choose your focus' })
    await picker.getByRole('radio', { name: label, exact: true }).check()
    await picker.getByLabel('Show', { exact: true }).selectOption('all')
    await picker.getByLabel('Find an item').fill(title)
    await picker.getByRole('button', { name: new RegExp(title) }).click()
    await picker.getByRole('button', { name: 'Choose item', exact: true }).click()
    await expect(page.getByRole('region', { name: 'Focusing on' })).toContainText(title)
    await page.getByRole('button', { name: 'Start focus', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Pause', exact: true })).toBeVisible()
    expect((await api(page, '/focus-sessions/active')).session[field]).toBe(entity.id)
    await page.getByRole('button', { name: 'Stop', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Start focus', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Remove', exact: true }).click()
  }
  await page.getByRole('tab', { name: 'Stopwatch', exact: true }).click()
  await page.getByRole('button', { name: 'Start stopwatch' }).click()
  await page.getByRole('button', { name: 'Lap', exact: true }).click()
  await expect(page.getByRole('list', { name: 'Laps' }).locator('li')).toHaveCount(1)
  await page.getByRole('tab', { name: 'Timer', exact: true }).click()
  await page.getByRole('button', { name: '15 min' }).click()
  await page.getByRole('button', { name: 'Start timer' }).click()
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  await page.getByRole('tab', { name: 'World Clock', exact: true }).click()
  await expect(page.getByRole('heading', { level: 2 })).toHaveText(['Local time', 'London', 'New York', 'Tokyo', 'Sydney'])
  const map = page.getByRole('img', { name: 'World map' })
  await expect(map).toBeVisible()
  const initialPins = await map.locator('[data-city-pin]').count()
  expect(initialPins).toBeGreaterThanOrEqual(4)
  for (const [width, height] of [[1920, 1080], [1366, 768], [390, 844]]) {
    await page.setViewportSize({ width, height })
    await page.screenshot({ path: `${root}/${browserName}-world-${width}.png`, fullPage: true })
    if (width >= 1366) expect(await page.evaluate(() => document.documentElement.scrollHeight)).toBeLessThanOrEqual(height + 1)
    expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([])
    await page.screenshot({ path: `${root}/${browserName}-world-${width}.png`, fullPage: true })
  }
  await page.setViewportSize({ width: 1366, height: 768 })
  await page.getByRole('button', { name: 'Add a city' }).click()
  await page.getByLabel('Search cities').fill('Oslo')
  await page.getByRole('dialog').getByRole('button', { name: /Oslo.*Europe/ }).click()
  await expect(page.getByRole('heading', { name: 'Oslo' })).toBeVisible()
  await expect(map.locator('[data-city-pin]')).toHaveCount(initialPins + 1)
  await page.getByRole('button', { name: 'Move earlier: Oslo' }).click()
  await expect(page.getByRole('heading', { level: 2 })).toHaveText(['Local time', 'London', 'New York', 'Tokyo', 'Oslo', 'Sydney'])
  await page.reload()
  await expect(page.getByRole('tab', { name: 'Focus', exact: true })).toHaveAttribute('aria-selected', 'true')
  await page.getByRole('tab', { name: 'World Clock', exact: true }).click()
  await expect(page.getByRole('heading', { level: 2 })).toHaveText(['Local time', 'London', 'New York', 'Tokyo', 'Oslo', 'Sydney'])
  await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuemax', '240')
  await page.getByRole('button', { name: 'Remove: Tokyo' }).click()
  await expect(page.getByRole('heading', { name: 'Tokyo' })).toHaveCount(0)
  await expect(map.locator('[data-city-pin]')).toHaveCount(initialPins)
  for (const city of ['London', 'New York', 'Oslo', 'Sydney']) await page.getByRole('button', { name: 'Remove: ' + city }).click()
  await page.reload()
  await page.getByRole('tab', { name: 'World Clock', exact: true }).click()
  await expect(page.getByRole('heading', { level: 2 })).toHaveText(['Local time'])
  expect(errors).toEqual([])
})

test('real focus and break deadlines transition while another route is open', async ({ page }) => {
  test.setTimeout(180000)
  await page.addInitScript(() => {
    const Audio = window.AudioContext
    window.focusAudioContexts = []
    if (Audio) window.AudioContext = class extends Audio { constructor(...args) { super(...args); window.focusAudioContexts.push(this) } }
  })
  await login(page)
  await page.goto('/focus')
  await page.getByRole('button', { name: /Custom Your rhythm/ }).click()
  const settings = page.getByRole('dialog', { name: 'Focus settings' })
  await settings.getByLabel('Focus minutes', { exact: true }).fill('1')
  await settings.getByLabel('Break minutes', { exact: true }).fill('1')
  await settings.getByLabel('Auto start breaks', { exact: true }).uncheck()
  await settings.getByLabel('Auto start next focus', { exact: true }).uncheck()
  await settings.getByRole('button', { name: 'Save settings' }).click()
  await page.getByRole('button', { name: 'Start focus', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Pause', exact: true })).toBeVisible()
  await expect.poll(() => page.evaluate(() => window.focusAudioContexts.map(context => context.state).join(','))).toContain('running')
  await page.getByRole('link', { name: 'Return to Today', exact: false }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Focus complete' })).toBeVisible({ timeout: 75000 })
  await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('link', { name: 'Focus', exact: true }).click()
  await expect(page.getByRole('timer')).toHaveText('00:00')
  await expect(page.getByText('Time for a 1 minute break.')).toBeVisible()
  await page.getByRole('button', { name: 'Start break', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Skip break' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Start next focus', exact: true })).toBeVisible({ timeout: 75000 })
  await expect(page.getByText('Ready for your next focus session.')).toBeVisible()
  await page.getByRole('button', { name: 'Start next focus', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Pause', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Stop', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Start focus', exact: true })).toBeVisible()
  expect((await api(page, '/progress')).progress.totalXp).toBe(0)
  expect((await api(page, '/focus-summary')).todaySeconds).toBeGreaterThanOrEqual(60)
})
