const { navigateTo, captureTask } = require('./navigation-helpers.cjs')
const { test, expect } = require('@playwright/test')

test('progression, lost-response retry, rewards and persisted focus work across screen sizes', async ({ page }) => {
  test.setTimeout(120000)
  page.setDefaultTimeout(15000)
  test.skip(!process.env.SMOKE_EMAIL || !process.env.SMOKE_PASSWORD, 'Use the isolated runner.')
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/today')
  await page.getByLabel('Email').fill(process.env.SMOKE_EMAIL)
  await page.getByLabel('Password').fill(process.env.SMOKE_PASSWORD)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Today', exact: true })).toBeVisible()
  await page.goto('/tasks/new')
  await page.getByLabel('Title', { exact: false }).fill('Phase 3 deliberate work')
  await page.getByLabel('Task size').selectOption('Large')
  await page.getByRole('button', { name: 'Create task', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Complete task', exact: true })).toBeVisible()
  const taskRoute = new URL(page.url()).pathname
  const identities = []
  await page.route('**/api/v1/tasks/*/complete', async route => {
    identities.push(route.request().headers().clientactionid)
    if (identities.length === 1) { await route.fetch(); await route.abort('failed') }
    else await route.continue()
  })
  await page.getByRole('button', { name: 'Complete task', exact: true }).click()
  await expect(page.getByRole('alert')).toBeVisible()
  await page.getByRole('button', { name: 'Complete task', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Reopen task', exact: true })).toBeVisible()
  expect(identities).toHaveLength(2)
  expect(identities[0]).toBeTruthy()
  expect(identities[0]).toBe(identities[1])
  await expect(page.getByRole('status').filter({ hasText: '+100 XP' })).toBeVisible()
  await page.unroute('**/api/v1/tasks/*/complete')
  await page.getByRole('button', { name: 'Reopen task', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: '-100 XP' })).toBeVisible()
  await page.getByRole('link', { name: 'Focus on this task', exact: true }).click()
  await page.getByRole('button', { name: 'Start focus', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Current focus' })).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Main navigation' })).not.toBeVisible()
  await page.getByRole('button', { name: 'Pause focus', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Resume focus', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('Paused · time is not counting')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Phase 3 deliberate work', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Resume focus', exact: true }).click()
  await page.getByRole('button', { name: 'Complete task & finish', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: '+100 XP' })).toBeVisible()
  await page.goto(taskRoute)
  await expect(page.getByRole('button', { name: 'Reopen task', exact: true })).toBeVisible()

  await page.goto('/rewards')
  await page.getByRole('button', { name: 'New reward' }).click()
  await page.getByLabel('Reward title').fill('An intentional reward')
  await page.getByLabel('Unlock at level').fill('1')
  await page.getByRole('button', { name: 'Create reward', exact: true }).click()
  await page.getByRole('region', { name: 'An intentional reward' }).getByRole('button', { name: 'Claim reward' }).click()
  await expect(page.getByRole('region', { name: 'An intentional reward' }).getByText('Claimed', { exact: true })).toBeVisible()
  await page.goto('/activity')
  await expect(page.getByText('Claimed: An intentional reward', { exact: true })).toBeVisible()
  await expect(page.getByText('Completed: Phase 3 deliberate work (+100 XP)', { exact: true })).toHaveCount(2)
  await expect(page.getByText('Reopened: Phase 3 deliberate work (-100 XP)', { exact: true })).toBeVisible()
  await page.goto('/focus')
  await page.getByRole('radio', { name: 'Focus without an item', exact: true }).check()
  await page.getByRole('button', { name: 'Start focus' }).click()
  await page.getByRole('button', { name: 'Pause focus' }).click()
  await expect(page.getByRole('button', { name: 'Resume focus', exact: true })).toBeVisible()

  for (const width of [375, 768, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    for (const route of ['/today', '/progress', '/activity', '/rewards', '/focus']) {
      await page.goto(route)
      await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
      if (route === '/focus') await expect(page.getByRole('button', { name: 'Resume focus' })).toBeVisible()
      if (route === '/progress') await expect(page.getByRole('progressbar', { name: 'Progress to next level', exact: true })).toBeVisible()
      if (route === '/activity') await expect(page.getByText('Claimed: An intentional reward', { exact: true })).toBeVisible()
      if (route === '/rewards') await expect(page.getByRole('region', { name: 'An intentional reward' })).toBeVisible()
      if (route === '/today') await expect(page.getByRole('region', { name: 'Tasks Today' })).toBeVisible()
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
      await page.screenshot({ path: `artifacts/phase3-${route.slice(1)}-${width}.png`, fullPage: true })
    }
    await page.getByRole('link', { name: 'Return to Today', exact: false }).focus()
    await page.keyboard.press('Enter')
    await expect(page.getByRole('heading', { name: 'Today', exact: true })).toBeVisible()
    if (width < 1200) {
      await page.getByRole('button', { name: 'Menu', exact: true }).click()
      await page.getByRole('dialog').getByRole('link', { name: 'Progress', exact: true }).click()
      await expect(page.getByRole('heading', { name: 'Progress', exact: true })).toBeVisible()
    }
  }
  expect(errors).toEqual([])
})
