const { test, expect } = require('@playwright/test')

test('XP, claims, activity and paused focus survive API restart', async ({ page }) => {
  test.skip(process.env.SMOKE_RESTART !== '1', 'Run after isolated API restart.')
  await page.goto('/focus')
  await page.getByLabel('Email').fill(process.env.SMOKE_EMAIL)
  await page.getByLabel('Password').fill(process.env.SMOKE_PASSWORD)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Resume focus' })).toBeVisible({ timeout: 15000 })
  await page.getByText('End without completing', { exact: true }).click()
  await page.getByRole('button', { name: 'Stop session', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Start focus' })).toBeVisible()
  await page.goto('/progress')
  await expect(page.getByRole('progressbar', { name: 'Progress to next level', exact: true })).toBeVisible()
  await page.getByText('XP ledger · awards and corrections', { exact: true }).click()
  await expect(page.getByText('-100 XP · Reversal', { exact: true })).toBeVisible()
  await page.goto('/rewards')
  await expect(page.getByRole('region', { name: 'An intentional reward' }).getByText('Claimed', { exact: true })).toBeVisible()
  await page.goto('/activity')
  await expect(page.getByText('Claimed: An intentional reward', { exact: true })).toBeVisible()
})
