const { test, expect } = require('@playwright/test')

test('plans and completes real tasks, habits and goals across responsive screens', async ({ page }) => {
  test.setTimeout(120000)
  page.setDefaultTimeout(10000)
  test.skip(!process.env.SMOKE_EMAIL || !process.env.SMOKE_PASSWORD, 'Supply a disposable owner for authenticated checks.')
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/today')
  await page.getByLabel('Email').fill(process.env.SMOKE_EMAIL)
  await page.getByLabel('Password').fill(process.env.SMOKE_PASSWORD)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Today', exact: true })).toBeVisible()
  await expect(page.getByLabel('Plan date')).toHaveValue(/^\d{4}-\d{2}-\d{2}$/)
  const date = await page.getByLabel('Plan date').inputValue()
  await page.getByLabel('Task title').fill('Prepare weekly plan')
  await page.getByRole('button', { name: 'Add to Inbox' }).click()
  await expect(page.getByText('Task captured.')).toBeVisible()
  await page.getByRole('link', { name: 'Inbox', exact: true }).click()
  await page.getByRole('link', { name: 'Prepare weekly plan', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Task details', exact: true })).toBeVisible()
  await expect(page.getByLabel('Title', { exact: false })).toHaveValue('Prepare weekly plan')
  await page.getByLabel('Title', { exact: false }).fill('Prepare weekly plan carefully')
  await page.getByLabel('Details', { exact: true }).fill('Choose three useful actions.')
  await page.getByLabel('Planned date').fill(date)
  await page.getByLabel('Due date').fill(date)
  await page.getByLabel('Priority', { exact: true }).selectOption('High')
  await page.getByRole('button', { name: 'Save task' }).click()
  await expect(page.getByText('Task saved.')).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('Title', { exact: false })).toHaveValue('Prepare weekly plan carefully')
  await expect(page.getByLabel('Planned date')).toHaveValue(date)
  await page.getByRole('link', { name: 'Today', exact: true }).click()
  await page.getByText('Choose a mission or add an existing task').click()
  await page.getByLabel('Task to plan').selectOption({ label: 'Prepare weekly plan carefully' })
  await page.getByRole('button', { name: 'Set Daily Mission' }).click()
  await expect(page.getByRole('region', { name: 'Daily Mission' }).getByRole('link', { name: 'Prepare weekly plan carefully' })).toBeVisible()
  await page.getByRole('button', { name: 'Complete mission' }).click()
  await expect(page.getByText('Mission completed.')).toBeVisible()
  await page.getByRole('button', { name: 'Reopen mission' }).click()
  await expect(page.getByRole('button', { name: 'Complete mission' })).toBeVisible()
  await page.getByRole('button', { name: 'Complete mission' }).click()
  await expect(page.getByText('Mission completed.')).toBeVisible()

  await page.getByRole('link', { name: 'Habits', exact: true }).click()
  await page.getByLabel('Habit title').fill('Read a chapter')
  await page.getByLabel('Schedule pattern').selectOption('WeeklyCount')
  await page.getByLabel('Weekly target').fill('3')
  await page.getByRole('button', { name: 'Create habit' }).click()
  await expect(page.getByRole('heading', { name: 'Read a chapter', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Log completion', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Undo completion' })).toBeVisible()
  await page.getByRole('button', { name: 'Undo completion' }).click()
  await expect(page.getByText('Reversed ·', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Log completion', exact: true }).click()
  const future = new Date(`${date}T12:00:00Z`)
  future.setUTCDate(future.getUTCDate() + 1)
  await page.getByLabel('Schedule starts').fill(future.toISOString().slice(0, 10))
  await page.getByLabel('Schedule pattern').selectOption('SelectedWeekdays')
  await page.getByRole('button', { name: 'Save future schedule' }).click()
  await expect(page.getByText('Future schedule saved.')).toBeVisible()
  await page.reload()
  await expect(page.getByText('3 times per week')).toBeVisible()
  await expect(page.getByText('Mon, Wed, Fri')).toBeVisible()
  await page.getByLabel('Habit title').fill('Read a chapter thoughtfully')
  await page.getByRole('button', { name: 'Save habit', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Read a chapter thoughtfully', exact: true })).toBeVisible()
  await page.getByLabel('Habit title').fill('Read a chapter')
  await page.getByRole('button', { name: 'Save habit', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Read a chapter', exact: true })).toBeVisible()

  await page.getByRole('link', { name: 'Goals', exact: true }).click()
  await page.getByLabel('Goal title').fill('Read ten chapters')
  await page.getByLabel('Goal type').selectOption('measured')
  await page.getByLabel('Baseline value').fill('0')
  await page.getByLabel('Target value').fill('10')
  await page.getByLabel('Unit').fill('chapters')
  await page.getByRole('button', { name: 'Create goal' }).click()
  await expect(page.getByRole('heading', { name: 'Read ten chapters', exact: true })).toBeVisible()
  await page.getByLabel('Current value (chapters)').fill('2')
  await page.getByLabel('Progress note').fill('First reading update')
  await page.getByRole('button', { name: 'Record progress' }).click()
  await expect(page.getByText('First reading update', { exact: true })).toBeVisible()
  await page.getByLabel('Current value (chapters)').fill('1')
  await page.getByLabel('Progress note').fill('Corrected reading update')
  await page.getByRole('button', { name: 'Record progress' }).click()
  await expect(page.getByText('Corrected reading update', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('First reading update', { exact: true })).toBeVisible()
  await expect(page.getByText('Corrected reading update', { exact: true })).toBeVisible()

  await page.getByLabel('Goal state').selectOption('Completed')
  await page.getByRole('button', { name: 'Save goal', exact: true }).click()
  await expect(page.getByText('Goal saved.', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('Goal state')).toHaveValue('Completed')

  for (const width of [375, 768, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    for (const route of ['/today', '/inbox', '/tasks', '/habits', '/goals', '/areas', '/settings']) {
      await page.goto(route)
      await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    }
  }
  // Carry out a write on the narrow screen, not just a layout check.
  await page.setViewportSize({ width: 375, height: 900 })
  await page.goto('/today')
  await page.getByLabel('Task title').fill('Mobile captured action')
  await page.getByRole('button', { name: 'Add to this day' }).click()
  await expect(page.getByRole('link', { name: 'Mobile captured action' })).toBeVisible()
  const mobileTask = page.getByRole('listitem').filter({ has: page.getByRole('link', { name: 'Mobile captured action', exact: true }) })
  await mobileTask.getByRole('button', { name: 'Cancel plan' }).click()
  await expect(mobileTask.getByText('Cancelled', { exact: false })).toBeVisible()
  await mobileTask.getByRole('button', { name: 'Commit to this day' }).click()
  await expect(mobileTask.getByRole('button', { name: 'Cancel plan' })).toBeVisible()
  await page.screenshot({ path: 'artifacts/phase2-today-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.screenshot({ path: 'artifacts/phase2-today-desktop.png', fullPage: true })
  expect(errors).toEqual([])
})
