const { navigateTo, captureTask } = require('./navigation-helpers.cjs')
const { test, expect } = require('@playwright/test')

test('productivity records survive an API process restart', async ({ page }) => {
  test.skip(process.env.SMOKE_RESTART !== '1', 'The isolated runner restarts the API before this check.')
  await page.goto('/today')
  await page.getByLabel('Email').fill(process.env.SMOKE_EMAIL)
  await page.getByLabel('Password').fill(process.env.SMOKE_PASSWORD)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByText('Mission completed.')).toBeVisible({ timeout: 15000 })
  await expect(page.getByRole('link', { name: 'Mobile captured action' })).toBeVisible()
  await navigateTo(page, 'Habits')
  await page.getByRole('navigation', { name: 'Habit views' }).getByRole('button', { name: 'Your routines' }).click()
  await page.getByRole('region', { name: 'Habit library' }).getByRole('link', { name: 'Read a chapter', exact: true }).click()
  await expect(page.getByText('3/week', { exact: true })).toBeVisible()
  await expect(page.getByText('Mon, Wed, Fri')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Undo completion' })).toBeVisible()
  await navigateTo(page, 'Goals')
  await page.getByRole('link', { name: 'Read ten chapters', exact: true }).click()
  await expect(page.getByText('First reading update', { exact: true })).toBeVisible()
  await expect(page.getByText('Corrected reading update', { exact: true })).toBeVisible()
})
