const { test, expect } = require('@playwright/test')

test('capture, keyboard dialogs, mobile navigation and recoverable failures work', async ({ page }) => {
  test.setTimeout(120000)
  test.skip(!process.env.SMOKE_EMAIL || !process.env.SMOKE_PASSWORD, 'Use the isolated browser runner.')
  await page.goto('/today')
  await page.getByLabel('Email').fill(process.env.SMOKE_EMAIL)
  await page.getByLabel('Password').fill(process.env.SMOKE_PASSWORD)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Today', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Skip to content' }).focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('#main-content')).toBeFocused()

  for (const width of [375, 768, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    const capture = page.getByRole('button', { name: width < 1200 ? 'Capture' : 'Quick Add', exact: true })
    await capture.click()
    const dialog = page.getByRole('dialog', { name: 'Capture a task' })
    await expect(dialog.getByLabel('Task title', { exact: false })).toBeFocused()
    await page.keyboard.press('Tab')
    await expect(dialog.getByRole('button', { name: 'Add to Inbox' })).toBeFocused()
    await page.keyboard.press('Tab')
    await page.keyboard.press('Tab')
    await expect(dialog.getByRole('button', { name: 'Close dialog' })).toBeFocused()
    await page.keyboard.press('Escape')
    await expect(dialog).not.toBeVisible()
    await expect(capture).toBeFocused()
    if (width < 1200) {
      await page.getByRole('button', { name: 'More', exact: true }).click()
      await page.getByRole('dialog', { name: 'Your workspace' }).getByRole('link', { name: 'Habits', exact: true }).click()
      await expect(page.getByRole('heading', { name: 'Habits', exact: true })).toBeVisible()
      await page.getByRole('button', { name: 'More', exact: true }).click()
      await page.getByRole('dialog', { name: 'Your workspace' }).getByRole('link', { name: 'Life Areas', exact: true }).click()
      await expect(page.getByRole('heading', { name: 'Life Areas' })).toBeVisible()
    }
  }

  await page.setViewportSize({ width: 375, height: 900 })
  await page.getByRole('button', { name: 'Capture', exact: true }).click()
  const captureDialog = page.getByRole('dialog', { name: 'Capture a task' })
  await captureDialog.getByLabel('Task title', { exact: false }).fill('Captured from anywhere')
  await page.route('**/api/v1/tasks', route => route.request().method() === 'POST'
    ? route.fulfill({ status: 503, contentType: 'application/problem+json', body: JSON.stringify({ title: 'Temporarily unavailable.' }) }) : route.continue())
  await captureDialog.getByRole('button', { name: 'Add to Inbox' }).click()
  await expect(captureDialog.getByRole('alert')).toContainText('Temporarily unavailable.')
  await expect(captureDialog.getByLabel('Task title', { exact: false })).toHaveValue('Captured from anywhere')
  await page.unroute('**/api/v1/tasks')
  await captureDialog.getByRole('button', { name: 'Add to Inbox' }).click()
  await expect(captureDialog.getByText('Task captured.')).toBeVisible()
  await page.keyboard.press('Escape')
  await page.goto('/inbox')
  await expect(page.getByRole('link', { name: 'Captured from anywhere' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('link', { name: 'Captured from anywhere' })).toBeVisible()
  await page.getByLabel('Search tasks').fill('A search with no matching actions')
  await expect(page.getByText('A little breathing room', { exact: true })).toBeVisible()
  await page.getByLabel('Search tasks').fill('')
  await page.getByRole('link', { name: 'Captured from anywhere' }).click()
  await page.locator('summary').filter({ hasText: /^Archive task$/ }).click()
  await page.getByRole('button', { name: 'Archive task', exact: true }).click()
  await expect(page.getByText('This task is archived. Its plans and completions are retained.')).toBeVisible()

  await page.goto('/goals')
  await page.getByRole('button', { name: 'New goal', exact: true }).click()
  await page.getByLabel('Goal title').fill('A thoughtful outcome')
  await page.getByRole('button', { name: 'Create goal', exact: true }).click()
  await page.getByLabel('Progress note').fill('A first step, recorded on mobile')
  await page.getByRole('button', { name: 'Record progress' }).click()
  await expect(page.getByRole('region', { name: 'Progress history' }).getByText('A first step, recorded on mobile')).toBeVisible()
  await page.getByRole('button', { name: 'Edit goal', exact: true }).click()
  await page.getByText('Archive this goal', { exact: true }).click()
  await page.getByRole('button', { name: 'Archive goal', exact: true }).click()
  await expect(page.getByText('Archived goal', { exact: true })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Progress history' }).getByText('A first step, recorded on mobile')).toBeVisible()

  await page.goto('/habits')
  await page.getByRole('button', { name: 'New habit', exact: true }).click()
  await page.getByLabel('Habit title').fill('A short daily pause')
  await page.getByRole('button', { name: 'Create habit', exact: true }).click()
  await page.getByRole('button', { name: 'Log completion', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Undo completion', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Edit habit', exact: true }).click()
  await page.getByText('Archive this habit', { exact: true }).click()
  await page.getByRole('button', { name: 'Archive habit', exact: true }).click()
  await expect(page.getByText('Archived routine', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Undo completion', exact: true })).toBeVisible()

  await page.route('**/api/v1/today', route => route.fulfill({ status: 503, contentType: 'application/problem+json', body: JSON.stringify({ title: 'Daily plan unavailable.' }) }))
  await page.goto('/today')
  await expect(page.getByRole('alert')).toContainText('Daily plan unavailable.')
  await page.unroute('**/api/v1/today')
  await page.getByRole('button', { name: 'Try again' }).click()
  await expect(page.getByRole('region', { name: 'Daily Mission' })).toBeVisible()
  await page.emulateMedia({ reducedMotion: 'reduce' })
  expect(await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--motion-fast').trim())).toBe('0ms')
})
