export const planningSearchCatalog = {
  'Planning mode': ['Planning mode', 'Planleggingsmodus', 'Planeringsläge', 'Planlægningstilstand'],
  Simple: ['Simple', 'Enkel', 'Enkel', 'Enkel'],
  'Focused Day': ['Focused Day', 'Fokusert dag', 'Fokuserad dag', 'Fokuseret dag'],
  Custom: ['Custom', 'Egendefinert', 'Egen', 'Tilpasset'],
  'Planning mode saved.': ['Planning mode saved.', 'Planleggingsmodus lagret.', 'Planeringsläget har sparats.', 'Planlægningstilstanden er gemt.'],
  'Planning mode could not be saved or loaded. Your work is unchanged.': ['Planning mode could not be saved or loaded. Your work is unchanged.', 'Planleggingsmodus kunne ikke lagres eller lastes. Arbeidet ditt er uendret.', 'Planeringsläget kunde inte sparas eller läsas in. Ditt arbete är oförändrat.', 'Planlægningstilstanden kunne ikke gemmes eller indlæses. Dit arbejde er uændret.'],
  'Loading settings…': ['Loading settings…', 'Laster innstillinger…', 'Läser in inställningar…', 'Indlæser indstillinger…'],
  'One daily list. Choose your next useful action.': ['One daily list. Choose your next useful action.', 'Én daglig liste. Velg din neste nyttige handling.', 'En daglig lista. Välj din nästa användbara handling.', 'Én daglig liste. Vælg din næste nyttige handling.'],
  'Your own rhythm. Use your mission, commitments and habits freely. Reusable templates are not available yet.': ['Your own rhythm. Use your mission, commitments and habits freely. Reusable templates are not available yet.', 'Din egen rytme. Bruk dagens hovedoppgave, planer og vaner fritt. Gjenbrukbare maler er ikke tilgjengelige ennå.', 'Din egen rytm. Använd dagens huvuduppgift, planer och vanor fritt. Återanvändbara mallar finns inte ännu.', 'Din egen rytme. Brug dagens hovedopgave, planer og vaner frit. Genanvendelige skabeloner er ikke tilgængelige endnu.'],
  'A balanced day with 3:3:3': ['A balanced day with 3:3:3', 'En balansert dag med 3:3:3', 'En balanserad dag med 3:3:3', 'En balanceret dag med 3:3:3'],
  'Three hours of meaningful work': ['Three hours of meaningful work', 'Tre timer med meningsfylt arbeid', 'Tre timmar meningsfullt arbete', 'Tre timers meningsfuldt arbejde'],
  'Protect time for your mission. Start focus when you are ready.': ['Protect time for your mission. Start focus when you are ready.', 'Sett av tid til hovedoppgaven. Start fokus når du er klar.', 'Avsätt tid för huvuduppgiften. Starta fokus när du är redo.', 'Sæt tid af til hovedopgaven. Start fokus, når du er klar.'],
  'Three shorter tasks': ['Three shorter tasks', 'Tre kortere oppgaver', 'Tre kortare uppgifter', 'Tre kortere opgaver'],
  'Choose a few supporting tasks from your daily plan.': ['Choose a few supporting tasks from your daily plan.', 'Velg noen støtteoppgaver fra dagsplanen.', 'Välj några stödjande uppgifter från dagsplanen.', 'Vælg nogle støtteopgaver fra dagsplanen.'],
  'Three maintenance activities': ['Three maintenance activities', 'Tre vedlikeholdsaktiviteter', 'Tre vardagsaktiviteter', 'Tre vedligeholdelsesaktiviteter'],
  'Make room for habits and everyday upkeep.': ['Make room for habits and everyday upkeep.', 'Gi plass til vaner og hverdagens gjøremål.', 'Ge plats för vanor och vardagens sysslor.', 'Giv plads til vaner og hverdagens gøremål.'],
  'A guide, not a quota. Your tasks stay together; choose what fits this day.': ['A guide, not a quota. Your tasks stay together; choose what fits this day.', 'En veiledning, ikke en kvote. Oppgavene dine holdes samlet; velg det som passer denne dagen.', 'En vägledning, ingen kvot. Dina uppgifter hålls samlade; välj det som passar dagen.', 'En vejledning, ikke en kvote. Dine opgaver holdes samlet; vælg det, der passer til dagen.'],
  'Daily list': ['Daily list', 'Dagsliste', 'Dagslista', 'Dagsliste'],
  'Search your workspace': ['Search your workspace', 'Søk i arbeidsområdet', 'Sök i arbetsytan', 'Søg i arbejdsområdet'],
  'Use arrows or Tab to browse, Enter to open and Escape to close.': ['Use arrows or Tab to browse, Enter to open and Escape to close.', 'Bruk piltaster eller Tab for å bla, Enter for å åpne og Escape for å lukke.', 'Använd pilar eller Tab för att bläddra, Enter för att öppna och Escape för att stänga.', 'Brug pile eller Tab til at gennemse, Enter til at åbne og Escape til at lukke.'],
  'Pages and actions': ['Pages and actions', 'Sider og handlinger', 'Sidor och åtgärder', 'Sider og handlinger'],
  'Matching records': ['Matching records', 'Treff', 'Träffar', 'Resultater'],
  'Recent and relevant': ['Recent and relevant', 'Nylig og relevant', 'Senaste och relevanta', 'Seneste og relevante'],
  'Searching…': ['Searching…', 'Søker…', 'Söker…', 'Søger…'],
  'Search could not load. Your pages and actions are still available.': ['Search could not load. Your pages and actions are still available.', 'Søket kunne ikke lastes. Sider og handlinger er fortsatt tilgjengelige.', 'Sökningen kunde inte läsas in. Sidor och åtgärder är fortfarande tillgängliga.', 'Søgningen kunne ikke indlæses. Sider og handlinger er stadig tilgængelige.'],
  'No matching records. Try another word.': ['No matching records. Try another word.', 'Ingen treff. Prøv et annet ord.', 'Inga träffar. Prova ett annat ord.', 'Ingen resultater. Prøv et andet ord.'],
  'Your tasks, goals, habits and Life Areas will appear here.': ['Your tasks, goals, habits and Life Areas will appear here.', 'Oppgaver, mål, vaner og livsområder vises her.', 'Uppgifter, mål, vanor och livsområden visas här.', 'Opgaver, mål, vaner og livsområder vises her.'],
  searchKind_task: ['Task', 'Oppgave', 'Uppgift', 'Opgave'],
  searchKind_goal: ['Goal', 'Mål', 'Mål', 'Mål'],
  searchKind_habit: ['Habit', 'Vane', 'Vana', 'Vane'],
  searchKind_area: ['Life Area', 'Livsområde', 'Livsområde', 'Livsområde'],
}
