export const deletionCatalog = {
  'Recently Deleted': ['Recently Deleted', 'Nylig slettet', 'Nyligen raderat', 'Slettet for nylig'],
  recentlyDeletedHint: ['Items remain here for 30 days before being permanently deleted.', 'Elementer blir liggende her i 30 dager før de slettes permanent.', 'Objekt ligger kvar här i 30 dagar innan de raderas permanent.', 'Elementer bliver her i 30 dage, før de slettes permanent.'],
  All: ['All', 'Alle', 'Alla', 'Alle'], Tasks: ['Tasks', 'Oppgaver', 'Uppgifter', 'Opgaver'], Habits: ['Habits', 'Vaner', 'Vanor', 'Vaner'], Goals: ['Goals', 'Mål', 'Mål', 'Mål'],
  Task: ['Task', 'Oppgave', 'Uppgift', 'Opgave'], Habit: ['Habit', 'Vane', 'Vana', 'Vane'], Goal: ['Goal', 'Mål', 'Mål', 'Mål'],
  Restore: ['Restore', 'Gjenopprett', 'Återställ', 'Gendan'],
  'Deleted today': ['Deleted today', 'Slettet i dag', 'Raderat idag', 'Slettet i dag'],
  'Delete permanently': ['Delete permanently', 'Slett permanent', 'Radera permanent', 'Slet permanent'],
  permanentDeleteTitle: ['Permanently delete this {type}?', 'Slette denne {type} permanent?', 'Radera denna {type} permanent?', 'Slette denne {type} permanent?'],
  permanentDeleteHint: ['This cannot be undone.', 'Dette kan ikke angres.', 'Detta går inte att ångra.', 'Dette kan ikke fortrydes.'],
  Cancel: ['Cancel', 'Avbryt', 'Avbryt', 'Annuller'],
  deletedAgo: ['Deleted {count} days ago', 'Slettet for {count} dager siden', 'Raderat för {count} dagar sedan', 'Slettet for {count} dage siden'],
  deletedAgoOne: ['Deleted 1 day ago', 'Slettet for 1 dag siden', 'Raderat för 1 dag sedan', 'Slettet for 1 dag siden'],
  deletesIn: ['Permanently deleted in {count} days', 'Slettes permanent om {count} dager', 'Raderas permanent om {count} dagar', 'Slettes permanent om {count} dage'],
  deletesInOne: ['Permanently deleted in 1 day', 'Slettes permanent om 1 dag', 'Raderas permanent om 1 dag', 'Slettes permanent om 1 dag'],
  'Nothing here': ['Nothing here', 'Ingenting her', 'Inget här', 'Intet her'],
  recentlyDeletedEmpty: ['Deleted Tasks, Habits, Goals and Life Areas will appear here for 30 days.', 'Slettede oppgaver, vaner, mål og livsområder vises her i 30 dager.', 'Raderade uppgifter, vanor, mål och livsområden visas här i 30 dagar.', 'Slettede opgaver, vaner, mål og livsområder vises her i 30 dage.'],
  Unassigned: ['Unassigned', 'Ikke tilordnet', 'Ej tilldelat', 'Ikke tildelt'],
  'New Life Area': ['New Life Area', 'Nytt livsområde', 'Nytt livsområde', 'Nyt livsområde'],
  'Create Life Area': ['Create Life Area', 'Opprett livsområde', 'Skapa livsområde', 'Opret livsområde'],
  'Custom image': ['Custom image', 'Eget bilde', 'Egen bild', 'Eget billede'],
  'Change image': ['Change image', 'Bytt bilde', 'Byt bild', 'Skift billede'],
  'Remove image': ['Remove image', 'Fjern bilde', 'Ta bort bild', 'Fjern billede'],
  'Horizontal focus': ['Horizontal focus', 'Vannrett fokus', 'Vågrätt fokus', 'Vandret fokus'],
  'Vertical focus': ['Vertical focus', 'Loddrett fokus', 'Lodrätt fokus', 'Lodret fokus'],
  deleteAreaTitle: ['Delete “{name}”?', 'Slette «{name}»?', 'Radera ”{name}”?', 'Slette “{name}”?'],
  deleteAreaImpact: ['This Life Area contains {tasks} Tasks, {habits} Habits and {goals} Goals.', 'Dette livsområdet inneholder {tasks} oppgaver, {habits} vaner og {goals} mål.', 'Detta livsområde innehåller {tasks} uppgifter, {habits} vanor och {goals} mål.', 'Dette livsområde indeholder {tasks} opgaver, {habits} vaner og {goals} mål.'],
  deleteAreaRelationships: ['These items stay intact and appear as Unassigned. Restoring the Life Area reconnects them.', 'Elementene beholdes og vises som Ikke tilordnet. Når livsområdet gjenopprettes, kobles de til igjen.', 'Objekten finns kvar och visas som Ej tilldelat. När livsområdet återställs kopplas de ihop igen.', 'Elementerne bevares og vises som Ikke tildelt. Når livsområdet gendannes, forbindes de igen.'],
  deleteSoftHint: ['It will move to Recently Deleted and can be restored for 30 days.', 'Det flyttes til Nylig slettet og kan gjenopprettes i 30 dager.', 'Det flyttas till Nyligen raderat och kan återställas i 30 dagar.', 'Det flyttes til Slettet for nylig og kan gendannes i 30 dage.'],
  'Delete task?': ['Delete task?', 'Slette oppgaven?', 'Radera uppgiften?', 'Slette opgaven?'],
  'Delete habit?': ['Delete habit?', 'Slette vanen?', 'Radera vanan?', 'Slette vanen?'],
  'Delete goal?': ['Delete goal?', 'Slette målet?', 'Radera målet?', 'Slette målet?'],
  'Delete Task': ['Delete Task', 'Slett oppgave', 'Radera uppgift', 'Slet opgave'],
  'Delete Habit': ['Delete Habit', 'Slett vane', 'Radera vana', 'Slet vane'],
  'Delete Goal': ['Delete Goal', 'Slett mål', 'Radera mål', 'Slet mål'],
  'Delete Life Area': ['Delete Life Area', 'Slett livsområde', 'Radera livsområde', 'Slet livsområde'],
  movedToDeleted: ['Moved to Recently Deleted.', 'Flyttet til Nylig slettet.', 'Flyttat till Nyligen raderat.', 'Flyttet til Slettet for nylig.'],
}
