export const dailyProgressCatalog = {
  'Add to today': ['Add to today', 'Legg til i dag', 'Lägg till idag', 'Tilføj til i dag'],
  addToDate: ['Add to {date}', 'Legg til {date}', 'Lägg till {date}', 'Tilføj til {date}'],
  taskDateMeaning: ['A planned date puts this task on that day. Inbox saves it without a date.', 'En planlagt dato viser oppgaven den dagen. Innboks lagrer uten dato.', 'Ett planerat datum visar uppgiften den dagen. Inkorgen sparar utan datum.', 'En planlagt dato viser opgaven den dag. Indbakke gemmer uden dato.'],
  'Tasks Today': ['Tasks Today', 'Dagens oppgaver', 'Dagens uppgifter', 'Dagens opgaver'],
  'Daily priority': ['Daily priority', 'Dagens prioritet', 'Dagens prioritet', 'Dagens prioritet'],
  'Choose a planned task': ['Choose a planned task', 'Velg en planlagt oppgave', 'Välj en planerad uppgift', 'Vælg en planlagt opgave'],
  priorityExplanation: ['An optional first priority from this day’s tasks. Start Focus when you are ready.', 'En valgfri førsteprioritet fra dagens oppgaver. Start Fokus når du er klar.', 'En valfri förstaprioritet bland dagens uppgifter. Starta Fokus när du är redo.', 'En valgfri førsteprioritet blandt dagens opgaver. Start Fokus, når du er klar.'],
  tasksTodayExplanation: ['Tasks planned for this date. Completed tasks stay visible.', 'Oppgaver planlagt denne datoen. Fullførte oppgaver blir synlige.', 'Uppgifter planerade för detta datum. Slutförda uppgifter visas fortfarande.', 'Opgaver planlagt til denne dato. Fuldførte opgaver forbliver synlige.'],
  'No Tasks planned for this day': ['No tasks planned for this day', 'Ingen oppgaver planlagt denne dagen', 'Inga uppgifter planerade denna dag', 'Ingen opgaver planlagt denne dag'],
  emptyTasksToday: ['Add a task or choose a date for an existing task in Inbox.', 'Legg til en oppgave eller velg dato for en oppgave i Innboks.', 'Lägg till en uppgift eller välj datum för en uppgift i Inkorgen.', 'Tilføj en opgave eller vælg dato for en opgave i Indbakke.'],
  'Open Inbox': ['Open Inbox', 'Åpne Innboks', 'Öppna Inkorgen', 'Åbn Indbakke'],
  "Today's Goals": ["Today's Goals", 'Dagens mål', 'Dagens mål', 'Dagens mål'],
  'Select a goal': ['Select a goal', 'Velg et mål', 'Välj ett mål', 'Vælg et mål'],
  'Select goal': ['Select goal', 'Velg mål', 'Välj mål', 'Vælg mål'],
  'Find a goal': ['Find a goal', 'Finn et mål', 'Hitta ett mål', 'Find et mål'],
  'No active goals match this view.': ['No active goals match this view.', 'Ingen aktive mål passer dette utvalget.', 'Inga aktiva mål matchar vyn.', 'Ingen aktive mål matcher visningen.'],
  'No Goals selected for this day': ['No goals selected for this day', 'Ingen mål valgt denne dagen', 'Inga mål valda denna dag', 'Ingen mål valgt denne dag'],
  emptyGoalsToday: ['Select an existing goal, or plan a task linked to a goal. Only relevant goals appear here.', 'Velg et mål, eller planlegg en oppgave knyttet til et mål. Bare relevante mål vises her.', 'Välj ett mål eller planera en uppgift kopplad till ett mål. Bara relevanta mål visas här.', 'Vælg et mål, eller planlæg en opgave knyttet til et mål. Kun relevante mål vises her.'],
  goalTasksToday: ['{count} linked tasks planned', '{count} tilknyttede oppgaver planlagt', '{count} kopplade uppgifter planerade', '{count} tilknyttede opgaver planlagt'],
  'Selected for this day': ['Selected for this day', 'Valgt for denne dagen', 'Valt för denna dag', 'Valgt til denne dag'],
  goalRetainedByTasks: ['Linked tasks keep this goal here even if you remove your selection.', 'Tilknyttede oppgaver beholder målet her selv om du fjerner valget.', 'Kopplade uppgifter behåller målet här även om du tar bort ditt val.', 'Tilknyttede opgaver beholder målet her, selv hvis du fjerner dit valg.'],
  'Continue': ['Continue', 'Fortsett', 'Fortsätt', 'Fortsæt'],
  'View Goal': ['View Goal', 'Vis mål', 'Visa mål', 'Vis mål'],
  'Remove selection': ['Remove selection', 'Fjern valg', 'Ta bort val', 'Fjern valg'],
  'Planning history': ['Planning history', 'Planhistorikk', 'Planeringshistorik', 'Planhistorik'],
  attentionExplanation: ['Earlier plans and deadlines to review. Plan an item for this day to add it to Tasks Today.', 'Tidligere planer og frister til gjennomgang. Planlegg en oppgave denne dagen for å vise den blant dagens oppgaver.', 'Tidigare planer och tidsfrister att granska. Planera en uppgift denna dag för att visa den bland dagens uppgifter.', 'Tidligere planer og frister til gennemgang. Planlæg en opgave denne dag for at vise den blandt dagens opgaver.'],
  planHistoryExplanation: ['Earlier selections are retained here. Their tasks keep their current planned dates.', 'Tidligere valg beholdes her. Oppgavene beholder sine gjeldende plandatoer.', 'Tidigare val finns kvar här. Uppgifterna behåller sina nuvarande planerade datum.', 'Tidligere valg bevares her. Opgaverne beholder deres aktuelle plandatoer.'],
  'Plan for this day': ['Plan for this day', 'Planlegg denne dagen', 'Planera denna dag', 'Planlæg denne dag'],
  upToXp: ['Up to {xp} XP', 'Opptil {xp} XP', 'Upp till {xp} XP', 'Op til {xp} XP'],
  'Linked goal': ['Linked goal', 'Tilknyttet mål', 'Kopplat mål', 'Tilknyttet mål'],
  habitXpRules: ['Choose 1–75 XP per completion. All habits share a 75 XP cap per scheduled local day; the actual award can be lower.', 'Velg 1–75 XP per fullføring. Alle vaner deler et tak på 75 XP per planlagt lokal dag; faktisk tildeling kan bli lavere.', 'Välj 1–75 XP per slutförande. Alla vanor delar ett tak på 75 XP per planerad lokal dag; den faktiska tilldelningen kan bli lägre.', 'Vælg 1–75 XP pr. fuldførelse. Alle vaner deler et loft på 75 XP pr. planlagt lokal dag; den faktiske tildeling kan være lavere.'],
  focusedDayGuide: ['Choose one priority, then work through your tasks, habits and goals at your own pace.', 'Velg én prioritet, og jobb med oppgaver, vaner og mål i ditt eget tempo.', 'Välj en prioritet och arbeta med uppgifter, vanor och mål i din egen takt.', 'Vælg én prioritet, og arbejd med opgaver, vaner og mål i dit eget tempo.'],
  customDayGuide: ['Your own rhythm. Use the daily sections and an optional priority freely.', 'Din egen rytme. Bruk dagens seksjoner og en valgfri prioritet fritt.', 'Din egen rytm. Använd dagens avsnitt och en valfri prioritet fritt.', 'Din egen rytme. Brug dagens sektioner og en valgfri prioritet frit.'],
  'Three meaningful work items': ['Three meaningful work items', 'Tre meningsfulle arbeidsoppgaver', 'Tre meningsfulla arbetsuppgifter', 'Tre meningsfulde arbejdsopgaver'],
  meaningfulWorkGuide: ['Choose three important things to move forward. Start Focus when you are ready.', 'Velg tre viktige ting å jobbe videre med. Start Fokus når du er klar.', 'Välj tre viktiga saker att arbeta vidare med. Starta Fokus när du är redo.', 'Vælg tre vigtige ting at arbejde videre med. Start Fokus, når du er klar.'],
  'Focus without an item': ['Focus without an item', 'Fokus uten tilknytning', 'Fokus utan koppling', 'Fokus uden tilknytning'],
  'Show': ['Show', 'Vis', 'Visa', 'Vis'],
  'All active': ['All active', 'Alle aktive', 'Alla aktiva', 'Alle aktive'],
  'Upcoming': ['Upcoming', 'Kommende', 'Kommande', 'Kommende'],
  'All priorities': ['All priorities', 'Alle prioriteter', 'Alla prioriteter', 'Alle prioriteter'],
  'Find an item': ['Find an item', 'Finn noe å jobbe med', 'Hitta något att arbeta med', 'Find noget at arbejde med'],
  'No items match. Try All active or another filter.': ['No items match. Try All active or another filter.', 'Ingen treff. Prøv Alle aktive eller et annet filter.', 'Inga träffar. Prova Alla aktiva eller ett annat filter.', 'Ingen resultater. Prøv Alle aktive eller et andet filter.'],
  'View habit': ['View habit', 'Vis vane', 'Visa vana', 'Vis vane'],
  'Rank System': ['Rank System', 'Rangsystem', 'Rangsystem', 'Rangsystem'],
  'Back to Progress': ['Back to Progress', 'Tilbake til Fremgang', 'Tillbaka till Framsteg', 'Tilbage til Fremskridt'],
  'Your progression through LIFEMAXING': ['Your progression through LIFEMAXING', 'Din fremgang gjennom LIFEMAXING', 'Din utveckling genom LIFEMAXING', 'Din udvikling gennem LIFEMAXING'],
  rankExplanation: ['Complete tasks and habits to earn XP, including work linked to your goals. XP increases your Level. Your Level determines your Rank and Division.', 'Fullfør oppgaver og vaner for å tjene XP, også arbeid knyttet til mål. XP øker nivået ditt. Nivået bestemmer rang og divisjon.', 'Slutför uppgifter och vanor för att få XP, även arbete kopplat till mål. XP höjer din nivå. Nivån bestämmer rang och division.', 'Fuldfør opgaver og vaner for at optjene XP, også arbejde knyttet til mål. XP øger dit niveau. Niveauet bestemmer rang og division.'],
  divisionExplanation: ['Within each rank: IV → III → II → I. Then the next rank begins at IV. Challenger I continues indefinitely.', 'Innen hver rang: IV → III → II → I. Neste rang starter på IV. Challenger I fortsetter uten grense.', 'Inom varje rang: IV → III → II → I. Nästa rang börjar på IV. Challenger I fortsätter utan gräns.', 'Inden for hver rang: IV → III → II → I. Næste rang starter ved IV. Challenger I fortsætter uden grænse.'],
  'Complete work': ['Complete work', 'Fullfør arbeid', 'Slutför arbete', 'Fuldfør arbejde'],
  'Level': ['Level', 'Nivå', 'Nivå', 'Niveau'],
  'Rank & Division': ['Rank & Division', 'Rang og divisjon', 'Rang och division', 'Rang og division'],
  'Current': ['Current', 'Nåværende', 'Nuvarande', 'Nuværende'],
  'Locked': ['Locked', 'Låst', 'Låst', 'Låst'],
  levelsAbove: ['Level {level} and above', 'Nivå {level} og høyere', 'Nivå {level} och högre', 'Niveau {level} og derover'],
  levelsRange: ['Levels {min}–{max}', 'Nivå {min}–{max}', 'Nivå {min}–{max}', 'Niveau {min}–{max}'],
  rankEmblem: ['{rank} rank emblem', 'Rangemblem for {rank}', 'Rangemblem för {rank}', 'Rangemblem for {rank}'],
  'Next rank': ['Next rank', 'Neste rang', 'Nästa rang', 'Næste rang'],
  'Next division': ['Next division', 'Neste divisjon', 'Nästa division', 'Næste division'],
  'Progress to next division': ['Progress to next division', 'Fremgang mot neste divisjon', 'Framsteg mot nästa division', 'Fremskridt mod næste division'],
  divisionXpRemaining: ['{xp} XP to Level {level}', '{xp} XP til nivå {level}', '{xp} XP till nivå {level}', '{xp} XP til niveau {level}'],
  'Highest division reached': ['Highest division reached', 'Høyeste divisjon nådd', 'Högsta divisionen uppnådd', 'Højeste division nået'],
  'View rank system': ['View rank system', 'Se rangsystemet', 'Visa rangsystemet', 'Se rangsystemet'],
  levelRules: ['Level 1 starts at 0 XP. The next level needs 500 XP, then each transition needs 100 more. Level rules v1; rank rules v2.', 'Nivå 1 starter på 0 XP. Neste nivå krever 500 XP, deretter krever hver overgang 100 mer. Nivåregler v1; rangregler v2.', 'Nivå 1 börjar vid 0 XP. Nästa nivå kräver 500 XP, därefter kräver varje övergång 100 mer. Nivåregler v1; rangregler v2.', 'Niveau 1 starter ved 0 XP. Næste niveau kræver 500 XP, derefter kræver hver overgang 100 mere. Niveauregler v1; rangregler v2.'],
  Iron: ['Iron', 'Jern', 'Järn', 'Jern'], Emerald: ['Emerald', 'Smaragd', 'Smaragd', 'Smaragd'],
  Master: ['Master', 'Mester', 'Mästare', 'Mester'], Grandmaster: ['Grandmaster', 'Stormester', 'Stormästare', 'Stormester'],
  Challenger: ['Challenger', 'Utfordrer', 'Utmanare', 'Udfordrer'],
}
