// <auto-generated />
using System;
using Lifemaxing.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lifemaxing.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922213031_FocusHubRefinement")]
    partial class FocusHubRefinement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lifemaxing.Api.Data.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Lifemaxing.Api.Data.LifeArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("CustomImage")
                        .HasColumnType("bytea");

                    b.Property<string>("CustomImageContentType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("CustomImageUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("ImageFocalX")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(50m);

                    b.Property<decimal>("ImageFocalY")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(50m);

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DeletedAtUtc");

                    b.HasIndex("UserId", "Key")
                        .IsUnique();

                    b.HasIndex("UserId", "SortOrder");

                    b.ToTable("LifeAreas", null, t =>
                        {
                            t.HasCheckConstraint("CK_LifeArea_CustomImage", "(\"CustomImage\" IS NULL AND \"CustomImageContentType\" IS NULL AND \"CustomImageUpdatedAtUtc\" IS NULL) OR (\"CustomImage\" IS NOT NULL AND \"CustomImageContentType\" IS NOT NULL AND \"CustomImageUpdatedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_LifeArea_ImageFocal", "\"ImageFocalX\" BETWEEN 0 AND 100 AND \"ImageFocalY\" BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("Lifemaxing.Api.Data.UserSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Density")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasDefaultValue("normal");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PlanningMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("FocusedDay");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasDefaultValue("system");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UiLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasDefaultValue("en");

                    b.HasKey("UserId");

                    b.ToTable("UserSettings", (string)null);
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Finance.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BillingInterval")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("NextBillingDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("Price")
                        .HasPrecision(11, 2)
                        .HasColumnType("numeric(11,2)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Status", "NextBillingDate");

                    b.ToTable("Subscriptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Subscriptions_Dates", "\"NextBillingDate\" >= \"StartDate\" AND \"StartDate\" >= DATE '1900-01-01' AND \"NextBillingDate\" <= DATE '9998-12-31'");

                            t.HasCheckConstraint("CK_Subscriptions_Interval", "\"BillingInterval\" IN ('Weekly', 'Monthly', 'Quarterly', 'Yearly')");

                            t.HasCheckConstraint("CK_Subscriptions_Price", "\"Price\" >= 0 AND \"Price\" <= 999999999.99");

                            t.HasCheckConstraint("CK_Subscriptions_Status", "\"Status\" IN ('Active', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Focus.FocusPreferences", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoBreak")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutoFocus")
                        .HasColumnType("boolean");

                    b.Property<bool>("BreakSound")
                        .HasColumnType("boolean");

                    b.Property<int>("DailyGoalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(120);

                    b.Property<bool>("FocusSound")
                        .HasColumnType("boolean");

                    b.Property<bool>("KeepAwake")
                        .HasColumnType("boolean");

                    b.Property<bool>("Notifications")
                        .HasColumnType("boolean");

                    b.Property<string>("Sound")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("SoundEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("Volume")
                        .HasColumnType("integer");

                    b.Property<bool>("WorldClockInitialized")
                        .HasColumnType("boolean");

                    b.HasKey("UserId");

                    b.ToTable("FocusPreferences", null, t =>
                        {
                            t.HasCheckConstraint("CK_FocusPreferences_DailyGoal", "\"DailyGoalMinutes\" BETWEEN 15 AND 1440 AND \"DailyGoalMinutes\" % 15 = 0");

                            t.HasCheckConstraint("CK_FocusPreferences_Volume", "\"Volume\" BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Focus.FocusRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BlockAutoStart")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ControllerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HabitId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("InterruptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PeriodIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("RemainingSeconds")
                        .HasColumnType("integer");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<int>("RuleVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"EndedAtUtc\" IS NULL");

                    b.ToTable("FocusRuns", null, t =>
                        {
                            t.HasCheckConstraint("CK_FocusRun_State", "\"RemainingSeconds\" >= 0 AND \"PeriodIndex\" >= 0 AND \"State\" IN ('Running','Paused','Interrupted','Ready','Ended') AND \"Phase\" IN ('Focus','Break')");
                        });
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Focus.FocusWorkSpan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FocusSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FocusSessionId");

                    b.HasIndex("UserId", "StartedAtUtc");

                    b.ToTable("FocusWorkSpans", null, t =>
                        {
                            t.HasCheckConstraint("CK_FocusSpan_Time", "\"EndedAtUtc\" >= \"StartedAtUtc\"");
                        });
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Focus.WorldClockCity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name", "TimeZoneId")
                        .IsUnique();

                    b.ToTable("WorldClockCities", (string)null);
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Goals.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("BaselineValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("Direction")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("LifeAreaId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("TargetValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LifeAreaId");

                    b.HasIndex("UserId", "ArchivedAtUtc");

                    b.HasIndex("UserId", "DeletedAtUtc");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Goals.GoalProgressEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.HasIndex("UserId", "GoalId", "RecordedAtUtc");

                    b.ToTable("GoalProgressEntries");
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Habits.Habit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LifeAreaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("XpPerLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.HasKey("Id");

                    b.HasIndex("LifeAreaId");

                    b.HasIndex("UserId", "ArchivedAtUtc");

                    b.HasIndex("UserId", "DeletedAtUtc");

                    b.ToTable("Habits", null, t =>
                        {
                            t.HasCheckConstraint("CK_Habit_Xp", "\"XpPerLog\" BETWEEN 1 AND 75");
                        });
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Habits.HabitLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HabitId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("LoggedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReversedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HabitId", "LocalDate")
                        .IsUnique()
                        .HasFilter("\"ReversedAtUtc\" IS NULL");

                    b.HasIndex("UserId", "LocalDate");

                    b.ToTable("HabitLogs");
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Habits.HabitSchedulePeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<int[]>("DaysOfWeek")
                        .HasColumnType("integer[]");

                    b.Property<DateOnly>("EffectiveFromDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveToDate")
                        .HasColumnType("date");

                    b.Property<Guid>("HabitId")
                        .HasColumnType("uuid");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("WeeklyTarget")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HabitId", "EffectiveFromDate")
                        .IsUnique();

                    b.ToTable("HabitSchedulePeriods", null, t =>
                        {
                            t.HasCheckConstraint("CK_Schedule_Pattern", "(\"Pattern\" = 'Daily' AND \"DaysOfWeek\" IS NULL AND \"WeeklyTarget\" IS NULL) OR (\"Pattern\" = 'SelectedWeekdays' AND cardinality(\"DaysOfWeek\") BETWEEN 1 AND 7 AND \"DaysOfWeek\" <@ ARRAY[1,2,3,4,5,6,7] AND \"WeeklyTarget\" IS NULL) OR (\"Pattern\" = 'WeeklyCount' AND \"WeeklyTarget\" BETWEEN 1 AND 7 AND \"DaysOfWeek\" IS NULL)");

                            t.HasCheckConstraint("CK_Schedule_Period", "\"EffectiveToDate\" IS NULL OR \"EffectiveToDate\" > \"EffectiveFromDate\"");
                        });
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Progression.ActivityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("LifeAreaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SourceEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubjectKind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "OccurredAtUtc");

                    b.HasIndex("UserId", "Kind", "SourceEventId")
                        .IsUnique()
                        .HasFilter("\"SourceEventId\" IS NOT NULL");

                    b.ToTable("ActivityEvents");
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Progression.CommandReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientActionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ResultId")
                        .HasColumnType("uuid");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ClientActionId")
                        .IsUnique();

                    b.ToTable("CommandReceipts");
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Progression.FocusSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AccumulatedSeconds")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FocusRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HabitId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PlannedSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("RunningSinceUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FocusRunId");

                    b.HasIndex("GoalId");

                    b.HasIndex("HabitId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"EndedAtUtc\" IS NULL");

                    b.HasIndex("UserId", "StartedAtUtc");

                    b.ToTable("FocusSessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Focus_Reference", "num_nonnulls(\"TaskId\", \"GoalId\", \"HabitId\") <= 1");

                            t.HasCheckConstraint("CK_Focus_State", "\"AccumulatedSeconds\" >= 0 AND (\"EndedAtUtc\" IS NULL OR \"EndedAtUtc\" >= \"StartedAtUtc\") AND ((\"Status\" = 'Running' AND \"RunningSinceUtc\" IS NOT NULL AND \"EndedAtUtc\" IS NULL) OR (\"Status\" = 'Paused' AND \"RunningSinceUtc\" IS NULL AND \"EndedAtUtc\" IS NULL) OR (\"Status\" IN ('Completed', 'Stopped', 'Cancelled') AND \"RunningSinceUtc\" IS NULL AND \"EndedAtUtc\" IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Progression.Reward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RequiredLevel");

                    b.ToTable("Rewards", null, t =>
                        {
                            t.HasCheckConstraint("CK_Reward_Level", "\"RequiredLevel\" BETWEEN 1 AND 100000");
                        });
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Progression.RewardClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RewardId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RewardId");

                    b.HasIndex("UserId", "ClaimedAtUtc");

                    b.HasIndex("UserId", "RewardId")
                        .IsUnique();

                    b.ToTable("RewardClaims");
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Progression.XpEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AmountSigned")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("LifeAreaId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RelatedEntryId")
                        .HasColumnType("uuid");

                    b.Property<int>("RuleVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RelatedEntryId");

                    b.HasIndex("UserId", "LifeAreaId");

                    b.HasIndex("UserId", "OccurredAtUtc");

                    b.HasIndex("UserId", "LocalDate", "Category");

                    b.HasIndex("UserId", "Kind", "SourceKind", "SourceId")
                        .IsUnique();

                    b.ToTable("XpEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_Xp_Sign", "(\"Kind\" = 'Award' AND \"AmountSigned\" >= 0 AND \"RelatedEntryId\" IS NULL) OR (\"Kind\" = 'Reversal' AND \"AmountSigned\" <= 0 AND \"RelatedEntryId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Tasks.TaskCompletion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AwardedXp")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ReversedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskId")
                        .IsUnique()
                        .HasFilter("\"ReversedAtUtc\" IS NULL");

                    b.HasIndex("UserId", "CompletedAtUtc");

                    b.ToTable("TaskCompletions");
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Tasks.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<int?>("EstimateMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LifeAreaId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("PlannedDate")
                        .HasColumnType("date");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.HasIndex("LifeAreaId");

                    b.HasIndex("UserId", "DueDate");

                    b.HasIndex("UserId", "PlannedDate", "DeletedAtUtc");

                    b.ToTable("Tasks", null, t =>
                        {
                            t.HasCheckConstraint("CK_Task_Estimate", "\"EstimateMinutes\" IS NULL OR \"EstimateMinutes\" BETWEEN 1 AND 10080");
                        });
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Today.DailyCommitment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CommittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("RemovedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId", "LocalDate");

                    b.HasIndex("UserId", "TaskId", "LocalDate")
                        .IsUnique();

                    b.ToTable("DailyCommitments");
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Today.DailyGoalSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("RemovedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("SelectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.HasIndex("UserId", "LocalDate", "GoalId")
                        .IsUnique();

                    b.ToTable("DailyGoalSelections");
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Today.DailyMission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("SelectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId", "LocalDate")
                        .IsUnique();

                    b.ToTable("DailyMissions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Lifemaxing.Api.Data.LifeArea", b =>
                {
                    b.HasOne("Lifemaxing.Api.Data.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lifemaxing.Api.Data.UserSettings", b =>
                {
                    b.HasOne("Lifemaxing.Api.Data.AppUser", "User")
                        .WithOne()
                        .HasForeignKey("Lifemaxing.Api.Data.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Finance.Subscription", b =>
                {
                    b.HasOne("Lifemaxing.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Focus.FocusPreferences", b =>
                {
                    b.HasOne("Lifemaxing.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Lifemaxing.Api.Features.Focus.FocusConfiguration", "Custom", b1 =>
                        {
                            b1.Property<Guid>("FocusPreferencesUserId")
                                .HasColumnType("uuid");

                            b1.Property<int>("BreakMinutes")
                                .HasColumnType("integer");

                            b1.Property<int>("FocusMinutes")
                                .HasColumnType("integer");

                            b1.Property<int>("LongBreakMinutes")
                                .HasColumnType("integer");

                            b1.Property<string>("Method")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("SessionsBeforeLongBreak")
                                .HasColumnType("integer");

                            b1.Property<int>("SmartMinutes")
                                .HasColumnType("integer");

                            b1.Property<int?>("TotalSessions")
                                .HasColumnType("integer");

                            b1.HasKey("FocusPreferencesUserId");

                            b1.ToTable("FocusPreferences");

                            b1.WithOwner()
                                .HasForeignKey("FocusPreferencesUserId");
                        });

                    b.Navigation("Custom")
                        .IsRequired();
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Focus.FocusRun", b =>
                {
                    b.HasOne("Lifemaxing.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Lifemaxing.Api.Features.Focus.FocusConfiguration", "Configuration", b1 =>
                        {
                            b1.Property<Guid>("FocusRunId")
                                .HasColumnType("uuid");

                            b1.Property<int>("BreakMinutes")
                                .HasColumnType("integer");

                            b1.Property<int>("FocusMinutes")
                                .HasColumnType("integer");

                            b1.Property<int>("LongBreakMinutes")
                                .HasColumnType("integer");

                            b1.Property<string>("Method")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("SessionsBeforeLongBreak")
                                .HasColumnType("integer");

                            b1.Property<int>("SmartMinutes")
                                .HasColumnType("integer");

                            b1.Property<int?>("TotalSessions")
                                .HasColumnType("integer");

                            b1.HasKey("FocusRunId");

                            b1.ToTable("FocusRuns");

                            b1.WithOwner()
                                .HasForeignKey("FocusRunId");
                        });

                    b.Navigation("Configuration")
                        .IsRequired();
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Focus.FocusWorkSpan", b =>
                {
                    b.HasOne("Lifemaxing.Api.Features.Progression.FocusSession", null)
                        .WithMany()
                        .HasForeignKey("FocusSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lifemaxing.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Focus.WorldClockCity", b =>
                {
                    b.HasOne("Lifemaxing.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Goals.Goal", b =>
                {
                    b.HasOne("Lifemaxing.Api.Data.LifeArea", null)
                        .WithMany()
                        .HasForeignKey("LifeAreaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lifemaxing.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Goals.GoalProgressEntry", b =>
                {
                    b.HasOne("Lifemaxing.Api.Features.Goals.Goal", null)
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lifemaxing.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Habits.Habit", b =>
                {
                    b.HasOne("Lifemaxing.Api.Data.LifeArea", null)
                        .WithMany()
                        .HasForeignKey("LifeAreaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lifemaxing.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Habits.HabitLog", b =>
                {
                    b.HasOne("Lifemaxing.Api.Features.Habits.Habit", null)
                        .WithMany()
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lifemaxing.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Habits.HabitSchedulePeriod", b =>
                {
                    b.HasOne("Lifemaxing.Api.Features.Habits.Habit", null)
                        .WithMany("Schedules")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Progression.ActivityEvent", b =>
                {
                    b.HasOne("Lifemaxing.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Progression.CommandReceipt", b =>
                {
                    b.HasOne("Lifemaxing.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Progression.FocusSession", b =>
                {
                    b.HasOne("Lifemaxing.Api.Features.Focus.FocusRun", null)
                        .WithMany()
                        .HasForeignKey("FocusRunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lifemaxing.Api.Features.Goals.Goal", null)
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lifemaxing.Api.Features.Habits.Habit", null)
                        .WithMany()
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lifemaxing.Api.Features.Tasks.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lifemaxing.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Progression.Reward", b =>
                {
                    b.HasOne("Lifemaxing.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Progression.RewardClaim", b =>
                {
                    b.HasOne("Lifemaxing.Api.Features.Progression.Reward", null)
                        .WithMany()
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lifemaxing.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Progression.XpEntry", b =>
                {
                    b.HasOne("Lifemaxing.Api.Features.Progression.XpEntry", null)
                        .WithMany()
                        .HasForeignKey("RelatedEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lifemaxing.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Tasks.TaskCompletion", b =>
                {
                    b.HasOne("Lifemaxing.Api.Features.Tasks.TaskItem", null)
                        .WithMany("Completions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lifemaxing.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Tasks.TaskItem", b =>
                {
                    b.HasOne("Lifemaxing.Api.Features.Goals.Goal", null)
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lifemaxing.Api.Data.LifeArea", null)
                        .WithMany()
                        .HasForeignKey("LifeAreaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lifemaxing.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Today.DailyCommitment", b =>
                {
                    b.HasOne("Lifemaxing.Api.Features.Tasks.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lifemaxing.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Today.DailyGoalSelection", b =>
                {
                    b.HasOne("Lifemaxing.Api.Features.Goals.Goal", null)
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lifemaxing.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Today.DailyMission", b =>
                {
                    b.HasOne("Lifemaxing.Api.Features.Tasks.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lifemaxing.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Lifemaxing.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Lifemaxing.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lifemaxing.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Lifemaxing.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Habits.Habit", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Lifemaxing.Api.Features.Tasks.TaskItem", b =>
                {
                    b.Navigation("Completions");
                });
#pragma warning restore 612, 618
        }
    }
}
