// English, Norwegian Bokmål, Swedish, Danish. User-entered names and notes stay unchanged.
export const financeCatalog = {
  subscriptionTitle: ['Subscriptions', 'Abonnementer', 'Abonnemang', 'Abonnementer'],
  subscriptionIntro: ['Keep track of recurring costs and the next date to review.', 'Hold oversikt over faste kostnader og neste dato du bør sjekke.', 'Håll koll på återkommande kostnader och nästa datum att granska.', 'Hold styr på faste udgifter og næste dato, du bør gennemgå.'],
  subscriptionCreate: ['Add subscription', 'Legg til abonnement', 'Lägg till abonnemang', 'Tilføj abonnement'],
  subscriptionEdit: ['Edit subscription', 'Rediger abonnement', 'Redigera abonnemang', 'Rediger abonnement'],
  subscriptionEditAction: ['Edit', 'Rediger', 'Redigera', 'Rediger'],
  subscriptionSave: ['Save subscription', 'Lagre abonnement', 'Spara abonnemang', 'Gem abonnement'],
  subscriptionName: ['Subscription name', 'Abonnementsnavn', 'Abonnemangets namn', 'Abonnementsnavn'],
  subscriptionCategory: ['Category', 'Kategori', 'Kategori', 'Kategori'],
  subscriptionPrice: ['Price per payment', 'Pris per betaling', 'Pris per betalning', 'Pris pr. betaling'],
  subscriptionCurrency: ['Currency', 'Valuta', 'Valuta', 'Valuta'],
  subscriptionInterval: ['Billing interval', 'Betalingsintervall', 'Betalningsintervall', 'Betalingsinterval'],
  subscriptionWeekly: ['Weekly', 'Ukentlig', 'Varje vecka', 'Ugentligt'],
  subscriptionMonthly: ['Monthly', 'Månedlig', 'Varje månad', 'Månedligt'],
  subscriptionQuarterly: ['Quarterly', 'Kvartalsvis', 'Varje kvartal', 'Kvartalsvis'],
  subscriptionYearly: ['Yearly', 'Årlig', 'Varje år', 'Årligt'],
  subscriptionStart: ['Start date', 'Startdato', 'Startdatum', 'Startdato'],
  subscriptionNext: ['Next billing date', 'Neste betalingsdato', 'Nästa betalningsdatum', 'Næste betalingsdato'],
  subscriptionNotes: ['Notes', 'Notater', 'Anteckningar', 'Noter'],
  subscriptionManualDates: ['Dates are tracked manually. Update the next billing date after checking your provider.', 'Datoer føres manuelt. Oppdater neste betalingsdato etter å ha sjekket leverandøren.', 'Datum registreras manuellt. Uppdatera nästa betalningsdatum efter att ha kontrollerat med leverantören.', 'Datoer registreres manuelt. Opdater næste betalingsdato efter at have tjekket hos udbyderen.'],
  subscriptionEstimates: ['Your recurring costs', 'Dine faste kostnader', 'Dina återkommande kostnader', 'Dine faste udgifter'],
  subscriptionEstimateHint: ['Estimates include all active subscriptions, with each currency kept separate.', 'Estimatene inkluderer alle aktive abonnementer, med hver valuta for seg.', 'Uppskattningarna omfattar alla aktiva abonnemang, med varje valuta separat.', 'Estimaterne omfatter alle aktive abonnementer, med hver valuta for sig.'],
  subscriptionPerMonth: ['per month, estimated', 'per måned, estimert', 'per månad, uppskattat', 'pr. måned, estimeret'],
  subscriptionPerYear: ['per year, estimated', 'per år, estimert', 'per år, uppskattat', 'pr. år, estimeret'],
  subscriptionNoActiveCosts: ['No active recurring costs recorded.', 'Ingen aktive faste kostnader registrert.', 'Inga aktiva återkommande kostnader registrerade.', 'Ingen aktive faste udgifter registreret.'],
  subscriptionCalculation: ['How estimates work', 'Slik beregnes estimatene', 'Så beräknas uppskattningarna', 'Sådan beregnes estimaterne'],
  subscriptionCalculationHint: ['Annual estimates use 52 weekly, 12 monthly, 4 quarterly or 1 yearly payment. Monthly estimates divide that annual total by 12. These are planning estimates, not a payment history. No currency conversion is applied.', 'Årsestimatet bruker 52 ukentlige, 12 månedlige, 4 kvartalsvise eller 1 årlig betaling. Månedsestimatet deler årssummen på 12. Dette er planleggingsestimater, ikke betalingshistorikk. Valuta omregnes ikke.', 'Årsuppskattningen använder 52 vecko-, 12 månads-, 4 kvartals- eller 1 årsbetalning. Månadsuppskattningen delar årssumman med 12. Detta är planeringsuppskattningar, inte betalningshistorik. Ingen valutaomräkning görs.', 'Årsestimatet bruger 52 ugentlige, 12 månedlige, 4 kvartalsvise eller 1 årlig betaling. Månedsestimatet deler årssummen med 12. Dette er planlægningsestimater, ikke betalingshistorik. Valuta omregnes ikke.'],
  subscriptionView: ['Subscription list', 'Abonnementsliste', 'Abonnemangslista', 'Abonnementsliste'],
  subscriptionActive: ['Active', 'Aktive', 'Aktiva', 'Aktive'],
  subscriptionCancelled: ['Cancelled', 'Avsluttede', 'Avslutade', 'Afsluttede'],
  subscriptionCount: ['{count} subscriptions', '{count} abonnementer', '{count} abonnemang', '{count} abonnementer'],
  subscriptionCountOne: ['{count} subscription', '{count} abonnement', '{count} abonnemang', '{count} abonnement'],
  subscriptionStatusSaved: ['Subscription status saved.', 'Abonnementsstatus lagret.', 'Abonnemangets status sparades.', 'Abonnementsstatus gemt.'],
  subscriptionEmpty: ['A clear view of recurring costs', 'Oversikt over faste kostnader', 'Överblick över återkommande kostnader', 'Overblik over faste udgifter'],
  subscriptionEmptyHint: ['Add a subscription with its price and next billing date to begin.', 'Legg til et abonnement med pris og neste betalingsdato for å begynne.', 'Lägg till ett abonnemang med pris och nästa betalningsdatum för att börja.', 'Tilføj et abonnement med pris og næste betalingsdato for at begynde.'],
  subscriptionCancelledEmpty: ['No cancelled subscriptions', 'Ingen avsluttede abonnementer', 'Inga avslutade abonnemang', 'Ingen afsluttede abonnementer'],
  subscriptionCancelledHint: ['Cancelled records stay here so you can review or reactivate them.', 'Avsluttede abonnementer beholdes her slik at du kan se eller aktivere dem igjen.', 'Avslutade abonnemang finns kvar här så att du kan granska eller återaktivera dem.', 'Afsluttede abonnementer gemmes her, så du kan gennemgå eller genaktivere dem.'],
  subscriptionUncategorized: ['Uncategorized', 'Uten kategori', 'Utan kategori', 'Uden kategori'],
  subscriptionOverdue: ['Needs review', 'Bør sjekkes', 'Behöver granskas', 'Bør gennemgås'],
  subscriptionCancel: ['Mark cancelled', 'Merk som avsluttet', 'Markera som avslutat', 'Markér som afsluttet'],
  subscriptionReactivate: ['Mark active', 'Merk som aktivt', 'Markera som aktivt', 'Markér som aktivt'],
  subscriptionTrackingOnly: ['Manual tracking only. Changing a record here does not cancel or change billing with your provider.', 'Kun manuell oversikt. Endringer her avslutter eller endrer ikke betaling hos leverandøren.', 'Endast manuell registrering. Ändringar här avslutar eller ändrar inte betalningen hos leverantören.', 'Kun manuel registrering. Ændringer her afslutter eller ændrer ikke betalingen hos udbyderen.'],
  subscriptionUpcoming: ['Next billing dates', 'Neste betalingsdatoer', 'Nästa betalningsdatum', 'Næste betalingsdatoer'],
  subscriptionUpcomingHint: ['The six earliest recorded dates, including dates that need review. They never advance automatically.', 'De seks tidligste registrerte datoene, inkludert datoer som bør sjekkes. De flyttes aldri automatisk.', 'De sex tidigaste registrerade datumen, även datum som behöver granskas. De flyttas aldrig automatiskt.', 'De seks tidligste registrerede datoer, også datoer der bør gennemgås. De flyttes aldrig automatisk.'],
  subscriptionOverdueCount: ['{count} past billing dates need review.', '{count} passerte betalingsdatoer bør sjekkes.', '{count} passerade betalningsdatum behöver granskas.', '{count} tidligere betalingsdatoer bør gennemgås.'],
  subscriptionNoUpcoming: ['No active billing dates recorded.', 'Ingen aktive betalingsdatoer registrert.', 'Inga aktiva betalningsdatum registrerade.', 'Ingen aktive betalingsdatoer registreret.'],
  subscriptionByCategory: ['By category', 'Etter kategori', 'Per kategori', 'Efter kategori'],
  subscriptionInvalidName: ['Enter a name of 1–200 characters.', 'Skriv et navn på 1–200 tegn.', 'Ange ett namn med 1–200 tecken.', 'Indtast et navn på 1–200 tegn.'],
  subscriptionInvalidCategory: ['Use at most 80 characters.', 'Bruk høyst 80 tegn.', 'Använd högst 80 tecken.', 'Brug højst 80 tegn.'],
  subscriptionInvalidPrice: ['Enter a price from 0 to 999999999.99 with at most two decimals.', 'Skriv en pris fra 0 til 999999999,99 med høyst to desimaler.', 'Ange ett pris från 0 till 999999999,99 med högst två decimaler.', 'Indtast en pris fra 0 til 999999999,99 med højst to decimaler.'],
  subscriptionInvalidDate: ['Choose a valid date between 1900 and 9998.', 'Velg en gyldig dato mellom 1900 og 9998.', 'Välj ett giltigt datum mellan 1900 och 9998.', 'Vælg en gyldig dato mellem 1900 og 9998.'],
  subscriptionDateOrder: ['Next billing date cannot be before start date.', 'Neste betalingsdato kan ikke være før startdatoen.', 'Nästa betalningsdatum kan inte vara före startdatumet.', 'Næste betalingsdato kan ikke være før startdatoen.'],
  subscriptionInvalidNotes: ['Use at most 2000 characters.', 'Bruk høyst 2000 tegn.', 'Använd högst 2000 tecken.', 'Brug højst 2000 tegn.'],
}
